create extension if not exists pgcrypto;

create table if not exists public.sales_leads (
  session_id text primary key,
  source text not null default 'landing-ciberseguridad',
  name text,
  email text,
  phone text,
  status text not null default 'new',
  score integer not null default 0 check (score >= 0 and score <= 100),
  objections text[] not null default '{}',
  last_message text,
  last_reply text,
  last_provider text,
  next_action text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sales_messages (
  id uuid primary key default gen_random_uuid(),
  session_id text not null references public.sales_leads(session_id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  provider text,
  score integer check (score is null or (score >= 0 and score <= 100)),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.sales_events (
  id uuid primary key default gen_random_uuid(),
  session_id text not null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists sales_leads_status_idx on public.sales_leads(status);
create index if not exists sales_leads_score_idx on public.sales_leads(score desc);
create index if not exists sales_leads_updated_at_idx on public.sales_leads(updated_at desc);
create index if not exists sales_messages_session_created_idx on public.sales_messages(session_id, created_at);
create index if not exists sales_events_session_created_idx on public.sales_events(session_id, created_at);
create index if not exists sales_events_event_type_idx on public.sales_events(event_type);

alter table public.sales_leads enable row level security;
alter table public.sales_messages enable row level security;
alter table public.sales_events enable row level security;

comment on table public.sales_leads is
  'Leads generated by the Ciberseguridad Proactiva e IA sales agent. Written only from Vercel serverless functions with the service role key.';

comment on table public.sales_messages is
  'Conversation turns for the sales agent. The browser must never write directly to this table.';

comment on table public.sales_events is
  'Widget events such as opens, Hotmart clicks, and lead capture.';
